version: '3.8'

services:
  postgres:
    image: postgres:17-alpine
    container_name: movie_db
    environment:
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
      POSTGRES_DB: ${DB_NAME:-movie_db}
    ports:
      - "5430:5432"

