"""message1

Revision ID: 43b57f50645b
Revises: 
Create Date: 2025-05-09 02:15:57.883025

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '43b57f50645b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('actor',
                    sa.Column('full_name', sa.String(length=255), nullable=False),
                    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
                    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
                    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('genre',
                    sa.Column('genre_name', sa.String(length=100), nullable=False),
                    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
                    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
                    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('genre_name')
                    )
    op.create_table('movie',
                    sa.Column('title_ru', sa.String(length=255), nullable=False),
                    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
                    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
                    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('movie_actors',
                    sa.Column('movie_id', sa.UUID(), nullable=False),
                    sa.Column('actor_id', sa.UUID(), nullable=False),
                    sa.ForeignKeyConstraint(['actor_id'], ['actor.id'], ondelete='CASCADE'),
                    sa.ForeignKeyConstraint(['movie_id'], ['movie.id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('movie_id', 'actor_id')
                    )
    op.create_table('movie_genres',
                    sa.Column('movie_id', sa.UUID(), nullable=False),
                    sa.Column('genre_id', sa.UUID(), nullable=False),
                    sa.ForeignKeyConstraint(['genre_id'], ['genre.id'], ondelete='CASCADE'),
                    sa.ForeignKeyConstraint(['movie_id'], ['movie.id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('movie_id', 'genre_id')
                    )
    op.create_table('movierating',
                    sa.Column('movie_id', sa.UUID(), nullable=False),
                    sa.Column('rating', sa.Numeric(precision=3, scale=1), nullable=False),
                    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
                    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
                    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
                    sa.ForeignKeyConstraint(['movie_id'], ['movie.id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('movie_id')
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('movierating')
    op.drop_table('movie_genres')
    op.drop_table('movie_actors')
    op.drop_table('movie')
    op.drop_table('genre')
    op.drop_table('actor')
    # ### end Alembic commands ###
